# Generated by Django 5.1.1 on 2025-01-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workassignment',
            name='work_nature',
            field=models.CharField(choices=[('manual', 'Manual'), ('machine', 'Machine'), ('other', 'Other')], max_length=50),
        ),
    ]
