# Generated by Django 5.1.1 on 2025-01-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_workassignment_work_nature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('1', 'Task 1 ELECTRICAL WORK'), ('2', 'Task 2 PLUMBING WORK'), ('3', 'Task 3 EARTH WORK'), ('4', 'Task 4 GARDENING WORK'), ('5', 'Task 5 CLEANING WORK'), ('6', 'Task 6 OTHER MANUAL WORK')], max_length=1)),
                ('work_nature', models.CharField(choices=[('manual', 'Manual'), ('machine', 'Machine'), ('other', 'Other')], max_length=10)),
                ('date', models.DateField()),
                ('session', models.CharField(max_length=10)),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('location', models.CharField(choices=[('Location 1', 'BOYS HOSTEL'), ('Location 2', 'GIRLS HOSTEL'), ('Location 3', 'STAFF QUARTERS'), ('Location 4', 'AS BLOCK'), ('Location 5', 'IB BLOCK'), ('Location 6', 'SF BLOCK'), ('Location 7', 'MECH BLOCK'), ('Location 8', 'AERO/RESEARCH BLOCK'), ('Location 9', 'MEDICAL CENTER')], max_length=100)),
                ('remarks', models.TextField()),
                ('staffs', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='WorkAssignment',
        ),
    ]
