# Generated by Django 5.1 on 2025-01-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_work_delete_workassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='session',
            field=models.CharField(choices=[('forenoon', 'Forenoon'), ('afternoon', 'Afternoon')], default='forenoon', max_length=10),
        ),
    ]
